name: Compile Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check:
    name: check
    if: github.repository == 'ynoproject/ynoengine'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ynoproject/buildscripts:master
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          path: ynoengine

      - run: cmake --preset yno-simd-release
        working-directory: ynoengine
        env:
          EASYRPG_BUILDSCRIPTS: "/root/workdir/buildscripts"
      - run: cmake --build --preset yno-simd-release
        working-directory: ynoengine

      - run: cmake --preset yno-release
        working-directory: ynoengine
        env:
          EASYRPG_BUILDSCRIPTS: "/root/workdir/buildscripts"
      - run: cmake --build --preset yno-release
        working-directory: ynoengine

      - uses: actions/upload-artifact@v4
        with:
          name: ynoengine-wasm
          path: |
            ynoengine/build/yno-simd-release/ynoengine-simd.*
            ynoengine/build/yno-release/ynoengine.*
          if-no-files-found: warn
